services:
  web:
    image: node:22.8
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_healthy

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: example
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --host=localhost --password=$$MYSQL_ROOT_PASSWORD
      timeout: 10s
      retries: 5

  valkey:
    image: valkey/valkey:8.0
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data
    healthcheck:
      test: valkey-cli ping
      timeout: 10s
      retries: 5

volumes:
  db_data:
  valkey_data:
